### ISSUE TITLE
Essential tools need to be bundled

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/clr-bundles#12]
1) dstat
2) glances
3) sysdig
4) sysstat
5)iostat
6) ioping
7) Chromium-browser
8) screen
9)mon
10)corefreq

**Comment by bryteise** [comment]
So we intentionally skip screen in favor of tmux. Chromium isn't very friendly for us to build and package so we have preferred Firefox. The rest we will look at carefully. Ping to @VictorRodriguez for looking at some of these since they seem squarely in performance monitoring and analysis.

**Comment by unixbhaskar** [comment]
@VictorRodriguez  what is your take on it ?

**Comment by VictorRodriguez** [comment]
I agree with @bryteise regarding Chromium and screen. For the rest of them, I am going to work on them, add them to the PNP-TOOLS bundle. Thanks for the request of new tools @unixbhaskar

**Comment by unixbhaskar** [comment]
@VictorRodriguez Thanks, But is there any specific reason to the name *PNP-TOOLS* ?? if not name it properly like ...*performance tools* ,*system-tools* et al ...just a suggestion..so people can pick it by looking at it and understand what it actually contains instead banging their head to decipher the naming conventions. Anyway, in UNIX, we have so many misnomers ..adding one more just doesn't make more sense.

All I am trying to say is, more explicit the outcome more people hook into it.

**Comment by VictorRodriguez** [comment]
@unixbhaskar is a good feedback, let me check with the team at IRC and ML and see what name could be more appropriate, sure is an easy fix problem :)

**Comment by fenrus75** [comment]
sysstat is already in pnp-tools-basic

**Comment by fenrus75** [comment]
screen->tmux is the same type of "wget or curl" discussion, some of it is taste, some of it is finger memory, and we may want a "old style unix tools" bundle for a few of those things that have modern replacements, but people still like to use.

chrome browser is a bit tricky for us;  ideally we'd have the official one but that is complicated in paperwork.

**Comment by bryteise** [comment]
So I actually didn't notice this but screen has seen new releases since 2014 (it previously hadn't been updated since 2008 or so). I'd be fine with adding that to the distro as is with tmux then similar to wget (hopefully less CVEs will follow). When that is done I'll consider this issue complete. I think @VictorRodriguez had a few follow ups on the packages he added too.

**Comment by VictorRodriguez** [comment]
@unixbhaskar  thanks a lot for this request, it helps us to increase our portfolio of tools. Here is a summary of the status of this request :  

dstat = already part of the bundle
glances = added 
sysdig = WIP, Is a good tool, but it needs more discussion since it needs kernel changes 
sysstat = already part of the bundle
iostat = already part of systat
ioping = added
Chromium-browser = We already have Firefox
screen = WIP, @bryteise  is working on it 
mon = insecure and old package. More discussion on the ML if you consider a must for your development environment 
corefreq = It requests kernel module, not secure. More discussion on the ML if you consider a must for your development environment 

Always open for feedback, regards

**Comment by bryteise** [comment]
screen is now in sysadmin-basic and sysdig is in performance-tools (which was added, pnp-tools still exists but just includes performance-tools now).
