### ISSUE TITLE
Please provide i3 wm

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/clr-bundles#20]
Kindly include i3 wm in the respective bundle. It is lightweight and fast , better than heavyweight stuff.

**Comment by bryteise** [comment]
This is a valid short coming you have identified. Because the window manager is getting started based on bundles installed and we have split out the bundles based on how intensive each window manager is to run (we have xfce4 for lower weight and gnome3 for heavier currently) it is not something that Clear currently would add though. Once we can provide finer grained packaging so that it is easier to have content rather than function level items, this would be something that could be considered for addition.

**Comment by nathanv** [comment]
+1 here
