### ISSUE TITLE
xz-utils compromised >= 5.6.0

### ISSUE THREAD

**Issue by Pamalosebi** [clearlinux/clr-bundles#255]
As it seems, was the xz-utils compromised. Please downgrade them to somewhere pre 5.6.0...

For reference:
[https://access.redhat.com/security/cve/CVE-2024-3094#cve-cvss-v3](https://access.redhat.com/security/cve/CVE-2024-3094#cve-cvss-v3)
[https://www.openwall.com/lists/oss-security/2024/03/29/4](https://www.openwall.com/lists/oss-security/2024/03/29/4)
[https://nvd.nist.gov/vuln/detail/CVE-2024-3094](https://nvd.nist.gov/vuln/detail/CVE-2024-3094)

**Comment by fenrus75** [comment]
41370 is rolling out already with this done

also we got lucky, our sshd did not link to liblzma ;)

there will be a 380 later today/early tomorrow that has xz usage removed
from as many places of the OS as possible since most of those were optional
stuffs and.. our patience with that just ended today,.

**Comment by fenrus75** [comment]
(if you cannot wait for the rollout,  "swupd update --format staging" gets
you to that release instantly)

**Comment by fenrus75** [comment]
(the 370 build rollout has reached my machines -- it might have reached
yours as well by now)
