### ISSUE TITLE
openssh-server: Missing /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by asifhg** [clearlinux/clr-bundles#45]
Bundle openssh-server does not install the default configuration file:
/etc/ssh/sshd_config

**Comment by AthenasJimenez** [comment]
That's totally normal and expected. Clear Linux is a stateless distribution, so we install all the default configs in /usr/share/defaults. You can do 2 thing here, copy the dir from /usr/share/defaults/ssh to /etc or create manually the directory /etc/ssh and finally create the file sshd_config.  

Please notice you should not edit/modify files in /usr/share/defaults!.

**Comment by asifhg** [comment]
`find /usr/share/defaults -name sshd_config ;# Produces nothing.`
Looks like sshd_config does not exist.
As a user I find it painful to reproduce the default sshd_config (template) file.
I might experience severe pain if I have to reproduce configuration files for other daemons if they don't exist in /usr/share/defaults. Then I might not be motivated to use ClearLinux.

**Comment by ahkok** [comment]
We do not publish a template file for `sshd_config` in `/usr/share/defaults` since that mechanism would cause sshd to read an entirely commented file on every startup for no reason.

We don't currently ship a `sshd_config` template file currently although we often put them under `/usr/share/doc`. In the case of `sshd_config`, I personally find that `man sshd_config` is sufficient to determine what options I want to set as it is far more detailed than the template `sshd_config` which doesn't actually explain what each option is and is therefore a better reference in almost any case.

I'll see about adding the template files to `/usr/share/doc` though.

**Comment by asifhg** [comment]
Turns out the defaults are compiled into sshd. I can dump the configuration by running:
`sudo /usr/sbin/sshd -T ;`
As a user, this a pain-point. But that's for the ClearLinux folks to decide. Hopefully you folks will consider that there are competing Linux distributions that may not be as painful. Thanks for your time, Jimenez!

**Comment by ahkok** [comment]
`sshd -T` isn't very useful indeed, even the template files are more readable.

@AthenasJimenez is adding the template files to `/usr/share/doc/openssh`, should be available in a day or so.

@asifhg Feel free to suggest other improvements that you may find!

**Comment by 3verlaster** [comment]
You can just create this file in this directory with:
nano sshd_config
then, CTRL+S and exit
![image](https://github.com/clearlinux/clr-bundles/assets/96373998/f40d1f80-d423-4ef7-af47-d6cc8838b171)
