### ISSUE TITLE
Python with tkinter does not work

### ISSUE THREAD

**Issue by m-mora** [clearlinux/clr-bundles#65]
when try to use graphic packages (base on tkinter ) in python it through an error  

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

what bundle needs to be installed in order to make this work?

**Comment by VictorRodriguez** [comment]
@m-mora it works in python2 
vrodri3@vrodri3-workstation ~/clearlinux/packages/python3 $ python2
Python 2.7.15 (default, Oct 24 2018, 20:05:15) 
[GCC 8.2.1 20180502] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tkinter
>>> import Tkinter
>>> Tkinter._test()
>>> 

fix for python3 wip

**Comment by VictorRodriguez** [comment]
python 3 fixed , patch that fix : 

diff --git a/python3.spec b/python3.spec
index e462443..a184a28 100644
--- a/python3.spec
+++ b/python3.spec
@@ -34,6 +34,9 @@ BuildRequires:  expat-dev
 BuildRequires:  libffi-dev
 BuildRequires:  procps-ng-bin
 BuildRequires:  netbase
+BuildRequires:  tk-dev
+BuildRequires:  tcl-dev
+BuildRequires:  libX11-dev
 Requires: python3-core
 Requires: python3-lib
 Requires: usrbinpython

**Comment by VictorRodriguez** [comment]
@m-mora please review and close : 

vrodri3@vrodri3-workstation ~/clearlinux $ sudo swupd update
Password:
Update started.
Version on server (25950) is not newer than system version (25950)
Update complete. System already up-to-date at version 25950
vrodri3@vrodri3-workstation ~/clearlinux $ python
Python 3.7.1 (default, Oct 29 2018, 16:37:42)
[GCC 8.2.1 20180502] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>>

**Comment by m-mora** [comment]
I tested and it works now, thank you @VictorRodriguez

**Comment by elegentFrog** [comment]
> when try to use graphic packages (base on tkinter ) in python it through an error
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>
>     import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> ```
> what bundle needs to be installed in order to make this work?



> 当尝试在python中使用图形包（基于tkinter）时通过错误
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>
>     import _tkinter # If this fails your Python may not be configured for Tk
> ModuleNotFoundError: No module named '_tkinter'
> ```
> 需要安装什么捆绑才能使这项工作？
Excuse me, how do you solve this problem？？

**Comment by elegentFrog** [comment]
I have been puzzled by this question for a long time

**Comment by VictorRodriguez** [comment]
@elegentFrog it works if you install python-extras

**Comment by elegentFrog** [comment]
Thank you very much!发自我的华为手机-------- 原始邮件 --------主题：Re: [clearlinux/clr-bundles] Python with tkinter does not work (#65)发件人：Victor Rodriguez 收件人：clearlinux/clr-bundles 抄送：elegentFrog <1270673774@qq.com>,Mention @elegentFrog it works if you install python-extras

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/clearlinux/clr-bundles","title":"clearlinux/clr-bundles","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/clearlinux/clr-bundles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@VictorRodriguez in #65: @elegentFrog it works if you install python-extras"}],"action":{"name":"View Issue","url":"https://github.com/clearlinux/clr-bundles/issues/65#issuecomment-465666050"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/clearlinux/clr-bundles/issues/65#issuecomment-465666050",
"url": "https://github.com/clearlinux/clr-bundles/issues/65#issuecomment-465666050",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
