### ISSUE TITLE
desktop-i3 doesn't run standalone

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/clr-bundles#76]
First of all, just like to say I totally appreciate the hard work being done on Clear and i3. Both are hidden gems that are made possible by all the fine work being done here. 

As per the issue, its tied to:  
https://github.com/clearlinux/clr-bundles/blob/master/bundles/desktop-i3

desktop-i3 bundle still relies on 'desktop' (gnome) dependencies. If I attempt to install i3 by itself, it doesn't work because of a raft of other dependency issues (gdm, xinit, X, etc). I was attempting to solve this myself but couldn't quite figure out how to do it yet. 

So in the end I ended up installing all of gnome desktop (default 'desktop' bundle) which is gigantic by comparison to the lean and fast i3. The system I'm building is very developer focussed so while gnome is nice, most of its contents are largely not required in this avatar.

**Comment by bryteise** [comment]
ping for @matthewrsj on his i3 setup

**Comment by matthewrsj** [comment]
Those are good points. I actually have the `desktop` bundle installed so I didn't see any issues setting it up (apart from the typical configuration munging). Bundles are supposed to supply all their dependencies and stand alone. i.e. if you install `desktop-i3` you should get `gdm`, `xinit`, `X`, etc. This is a bug in the `desktop-i3` bundle.

I see two options:
1) someone do the work to provide the trimmed-down dependencies in the bundle definition file for `desktop-i3`
2) as a stop-gap measure `include(desktop)` in the `desktop-i3` bundle definition file.

Pinging @ahkok here because he's listed as the maintainer of this bundle.

**Comment by matthewrsj** [comment]
I'll also note that this bundle is listed as `WIP` but I've been using it for quite a while with no issues. I think once the dependencies issue is resolved this could be updated to `Active`

**Comment by harsh-telepathy** [comment]
@ahkok : I agree. Having a login screen is redundant too so gdm isn't needed. Having the x bundle (or even better, wayland) would be damn useful.

**Comment by fenrus75** [comment]
we're working on it now
will be a few iterations to get this great

**Comment by harsh-telepathy** [comment]
Please could we also add flatpak support. Will allow installing a bunch of 3rd party apps to work with i3

**Comment by matthewrsj** [comment]
Maybe we need a package-level `flatpak` bundle instead of requiring users to pull in all of `os-utils-gui` or `desktop-apps`

**Comment by ahkok** [comment]
please make the `flatpak` request a separate feature request.

**Comment by harsh-telepathy** [comment]
> please make the `flatpak` request a separate feature request.

Done.

**Comment by dedguy21** [comment]
Just curious if a flatpak was built? 

Then wondering if we could do something similar with Awesome WM
